Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/user/.pyenv/versions/3.12.11/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from tidychef import acquire, preview
from tidychef.direction import right
from tidychef.selection import CsvSelectable, filters
from tidychef.output import TidyData, Column

# this is our custom function for apply
def lennon_iser(cell_value: str):
    """
    A simple function to prefix " Lennon" where the value of
    a cell is "John"
    """
    if cell_value == "John":
        return cell_value+" Lennon"
    return cell_value


table: CsvSelectable = acquire.csv.http("https://raw.githubusercontent.com/mikeAdamss/tidychef/main/tests/fixtures/csv/bands-wide.csv")

observations = table.filter(filters.is_numeric).label_as("Observations")
members = (table.excel_ref("B") | table.excel_ref("H")).is_not_blank().label_as("Members")
preview(observations, members)

tidy_data = TidyData(
    observations,
    Column(members.finds_observations_directly(right), apply=lennon_iser)
)
print(tidy_data)
------------------


[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[2][39m[32m, line 25[39m
[32m     20[39m members = (table.excel_ref([33m"[39m[33mB[39m[33m"[39m) | table.excel_ref([33m"[39m[33mH[39m[33m"[39m)).is_not_blank().label_as([33m"[39m[33mMembers[39m[33m"[39m)
[32m     21[39m preview(observations, members)
[32m     23[39m tidy_data = TidyData(
[32m     24[39m     observations,
[32m---> [39m[32m25[39m     Column([43mmembers[49m[43m.[49m[43mfinds_observations_directly[49m(right), apply=lennon_iser)
[32m     26[39m )
[32m     27[39m [38;5;28mprint[39m(tidy_data)

[31mAttributeError[39m: 'CsvSelectable' object has no attribute 'finds_observations_directly'

