Traceback (most recent call last):
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from typing import List
from datachef import acquire, XlsxSelectable, matches, TidyData, Column, down, right

tables: List[XlsxSelectable] = acquire.xlsx.http("https://github.com/mikeAdamss/datachef/raw/main/tests/fixtures/xlsx/ons-oic.xlsx")
table = tables[9]

observations = table.excel_ref("B7:H10").label_as("Observations")
housing = table.excel_ref("B6").expand(right).label_as("Dataset Identifier Code")

# Note: matches a regex of capital Z followed by anything
tidy_data = TidyData(
    observations,
    Column(dataset_identifier_code.finds_observations_directly(down), validation=matches.regex("Z.*"))
)

print(tidy_data)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[3], line 16[0m
[1;32m     10[0m [38;5;66;03m# Note: matches a regex of capital Z followed by anything[39;00m
[1;32m     11[0m tidy_data [38;5;241m=[39m TidyData(
[1;32m     12[0m     observations,
[1;32m     13[0m     Column(dataset_identifier_code[38;5;241m.[39mfinds_observations_directly(down), validation[38;5;241m=[39mmatches[38;5;241m.[39mregex([38;5;124m"[39m[38;5;124mZ.*[39m[38;5;124m"[39m))
[1;32m     14[0m )
[0;32m---> 16[0m [38;5;28;43mprint[39;49m[43m([49m[43mtidy_data[49m[43m)[49m

File [0;32m~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/datachef/output/tidydata.py:68[0m, in [0;36mTidyData.__str__[0;34m(self)[0m
[1;32m     67[0m [38;5;28;01mdef[39;00m [38;5;21m__str__[39m([38;5;28mself[39m):  [38;5;66;03m# pragma: no cover[39;00m
[0;32m---> 68[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__get_representation[49m[43m([49m[43m)[49m

File [0;32m~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/datachef/output/tidydata.py:51[0m, in [0;36mTidyData.__get_representation[0;34m(self)[0m
[1;32m     47[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m     48[0m [38;5;124;03mRepresentation logic shared by __str__ and __repr__[39;00m
[1;32m     49[0m [38;5;124;03m"""[39;00m
[1;32m     50[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_data:
[0;32m---> 51[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_transform[49m[43m([49m[43m)[49m
[1;32m     53[0m header_row [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_data[[38;5;241m0[39m]
[1;32m     54[0m data_rows [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_data[[38;5;241m1[39m:]

File [0;32m~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/datachef/output/tidydata.py:210[0m, in [0;36mTidyData._transform[0;34m(self)[0m
[1;32m    204[0m standard_columns [38;5;241m=[39m [
[1;32m    205[0m     x
[1;32m    206[0m     [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mcolumns
[1;32m    207[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(x[38;5;241m.[39mengine, HorizontalCondition)
[1;32m    208[0m ]
[1;32m    209[0m [38;5;28;01mfor[39;00m column [38;5;129;01min[39;00m standard_columns:
[0;32m--> 210[0m     ob_value [38;5;241m=[39m [43mcolumn[49m[38;5;241;43m.[39;49m[43mresolve_column_cell_from_obs_cell[49m[43m([49m
[1;32m    211[0m [43m        [49m[43mobservation[49m
[1;32m    212[0m [43m    [49m[43m)[49m[38;5;241m.[39mvalue
[1;32m    213[0m     line[38;5;241m.[39mappend(ob_value)
[1;32m    214[0m     column_value_dict[column[38;5;241m.[39mlabel] [38;5;241m=[39m ob_value

File [0;32m~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/datachef/column/base.py:91[0m, in [0;36mBaseColumn.resolve_column_cell_from_obs_cell[0;34m(self, observation_cell, *args)[0m
[1;32m     81[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m     82[0m [38;5;124;03mUse the provided lookup engine to return the value[39;00m
[1;32m     83[0m [38;5;124;03mof this Column against a given observation, according[39;00m
[0;32m   (...)[0m
[1;32m     88[0m [38;5;124;03msome sort.[39;00m
[1;32m     89[0m [38;5;124;03m"""[39;00m
[1;32m     90[0m cell [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mengine[38;5;241m.[39mresolve(observation_cell, [38;5;241m*[39margs)
[0;32m---> 91[0m cell [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_post_lookup[49m[43m([49m[43mcell[49m[43m)[49m
[1;32m     92[0m [38;5;28;01mreturn[39;00m cell

File [0;32m~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/datachef/column/column.py:76[0m, in [0;36mColumn._post_lookup[0;34m(self, cell)[0m
[1;32m     74[0m [38;5;66;03m# Validate[39;00m
[1;32m     75[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mvalidation:
[0;32m---> 76[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mvalidation[49m[43m([49m[43mcell[49m[43m)[49m
[1;32m     78[0m [38;5;28;01mreturn[39;00m cell

File [0;32m~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/datachef/validation/matcher.py:57[0m, in [0;36mMatcher.__call__[0;34m(self, cell)[0m
[1;32m     55[0m     [38;5;28mprint[39m([38;5;28mstr[39m(err))
[1;32m     56[0m [38;5;28;01melse[39;00m:
[0;32m---> 57[0m     [38;5;28;01mraise[39;00m err

File [0;32m~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/datachef/validation/matcher.py:38[0m, in [0;36mMatcher.__call__[0;34m(self, cell)[0m
[1;32m     36[0m [38;5;28;01mtry[39;00m:
[1;32m     37[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mmatch_regex:
[0;32m---> 38[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__regex_implemented[49m[43m([49m[43mcell[49m[43m)[49m
[1;32m     39[0m     [38;5;28;01melse[39;00m:
[1;32m     40[0m         [38;5;66;03m# Catch and help any users calling without configuring[39;00m
[1;32m     41[0m         [38;5;28;01mraise[39;00m NoMatcherSpecifiedError(
[1;32m     42[0m [38;5;250m            [39m[38;5;124;03m"""[39;00m
[1;32m     43[0m [38;5;124;03m            You are passing a cell to a Matcher that has not[39;00m
[0;32m   (...)[0m
[1;32m     49[0m [38;5;124;03m            """[39;00m
[1;32m     50[0m         )

File [0;32m~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/datachef/validation/matcher.py:80[0m, in [0;36mMatcher.__regex_implemented[0;34m(self, cell)[0m
[1;32m     76[0m [38;5;28;01mdef[39;00m [38;5;21m__regex_implemented[39m([38;5;28mself[39m, cell: Cell):
[1;32m     77[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m     78[0m [38;5;124;03m    Actually do regex matching[39;00m
[1;32m     79[0m [38;5;124;03m    """[39;00m
[0;32m---> 80[0m     [38;5;28;01massert[39;00m re[38;5;241m.[39mmatch(
[1;32m     81[0m         [38;5;28mself[39m[38;5;241m.[39mregex_pattern, cell[38;5;241m.[39mvalue
[1;32m     82[0m     ), [38;5;124mf[39m[38;5;124m'[39m[38;5;124mValue of cell [39m[38;5;124m"[39m[38;5;132;01m{[39;00mcell[38;5;132;01m}[39;00m[38;5;124m"[39m[38;5;124m does not match provided regex pattern [39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mregex_pattern[38;5;132;01m}[39;00m[38;5;124m"[39m[38;5;124m.[39m[38;5;124m'[39m

[0;31mAssertionError[0m: Value of cell "<B6, value:"MVO6", x:1, y:5>" does not match provided regex pattern "Z.*".

