Traceback (most recent call last):
  File "/Users/michaeladams/Library/Caches/pypoetry/virtualenvs/tidychef-jGQs3W5N-py3.7/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/Users/michaeladams/Library/Caches/pypoetry/virtualenvs/tidychef-jGQs3W5N-py3.7/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/michaeladams/Library/Caches/pypoetry/virtualenvs/tidychef-jGQs3W5N-py3.7/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/michaeladams/Library/Caches/pypoetry/virtualenvs/tidychef-jGQs3W5N-py3.7/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/michaeladams/.pyenv/versions/3.7.13/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/michaeladams/Library/Caches/pypoetry/virtualenvs/tidychef-jGQs3W5N-py3.7/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/michaeladams/Library/Caches/pypoetry/virtualenvs/tidychef-jGQs3W5N-py3.7/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/michaeladams/Library/Caches/pypoetry/virtualenvs/tidychef-jGQs3W5N-py3.7/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from tidychef import acquire, against
from tidychef.selection import CsvSelectable

table: CsvSelectable = acquire.csv.http("https://raw.githubusercontent.com/mikeAdamss/tidychef/main/tests/fixtures/csv/bands-wide.csv")

table.excel_ref('B').is_not_blank().validate(against.regex("John"), raise_first_error=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mCellValidationError[0m                       Traceback (most recent call last)
[0;32m/var/folders/3q/wpcx20553xv0hpsjgtq_zl_m0000gp/T/ipykernel_64254/570008862.py[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0mtable[0m[0;34m:[0m [0mCsvSelectable[0m [0;34m=[0m [0macquire[0m[0;34m.[0m[0mcsv[0m[0;34m.[0m[0mhttp[0m[0;34m([0m[0;34m"https://raw.githubusercontent.com/mikeAdamss/tidychef/main/tests/fixtures/csv/bands-wide.csv"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m
[0;32m----> 6[0;31m [0mtable[0m[0;34m.[0m[0mexcel_ref[0m[0;34m([0m[0;34m'B'[0m[0;34m)[0m[0;34m.[0m[0mis_not_blank[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mvalidate[0m[0;34m([0m[0magainst[0m[0;34m.[0m[0mregex[0m[0;34m([0m[0;34m"John"[0m[0;34m)[0m[0;34m,[0m [0mraise_first_error[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/Library/Caches/pypoetry/virtualenvs/tidychef-jGQs3W5N-py3.7/lib/python3.7/site-packages/tidychef/selection/selectable.py[0m in [0;36mvalidate[0;34m(self, validator, raise_first_error)[0m
[1;32m    501[0m [0mfollowing[0m [0mvalidation[0m [0merror[0m [0mwas[0m [0mencountered[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    502[0m [0;34m{[0m[0mvalidator[0m[0;34m.[0m[0mmsg[0m[0;34m([0m[0mcell[0m[0;34m)[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 503[0;31m                 ''')
[0m[1;32m    504[0m                 [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    505[0m                     [0mvalidation_errors[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mvalidator[0m[0;34m.[0m[0mmsg[0m[0;34m([0m[0mcell[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mCellValidationError[0m: 
When making selections from table: Unnamed Table the
following validation error was encountered:
"Paul" does not match pattern: "John"
                
CellValidationError: 
When making selections from table: Unnamed Table the
following validation error was encountered:
"Paul" does not match pattern: "John"
                

