Traceback (most recent call last):
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/michaeladams/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from typing import List
from datachef import acquire, XlsxSelectable

tables: List[XlsxSelectable] = acquire.xlsx.http("https://github.com/mikeAdamss/datachef/raw/main/tests/fixtures/xlsx/ons-oic.xlsx")
tables[7].excel_ref('A1:A2').assert_one()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[3], line 5[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdatachef[39;00m [38;5;28;01mimport[39;00m acquire, XlsxSelectable
[1;32m      4[0m tables: List[XlsxSelectable] [38;5;241m=[39m acquire[38;5;241m.[39mxlsx[38;5;241m.[39mhttp([38;5;124m"[39m[38;5;124mhttps://github.com/mikeAdamss/datachef/raw/main/tests/fixtures/xlsx/ons-oic.xlsx[39m[38;5;124m"[39m)
[0;32m----> 5[0m [43mtables[49m[43m[[49m[38;5;241;43m7[39;49m[43m][49m[38;5;241;43m.[39;49m[43mexcel_ref[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mA1:A2[39;49m[38;5;124;43m'[39;49m[43m)[49m[38;5;241;43m.[39;49m[43massert_one[49m[43m([49m[43m)[49m

File [0;32m~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/datachef/selection/selectable.py:63[0m, in [0;36mSelectable.assert_one[0;34m(self)[0m
[1;32m     59[0m [38;5;28;01mdef[39;00m [38;5;21massert_one[39m([38;5;28mself[39m):
[1;32m     60[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m     61[0m [38;5;124;03m    Assert that the current selection contains exactly one cell[39;00m
[1;32m     62[0m [38;5;124;03m    """[39;00m
[0;32m---> 63[0m     [38;5;28;01massert[39;00m (
[1;32m     64[0m         [38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39mcells) [38;5;241m==[39m [38;5;241m1[39m
[1;32m     65[0m     ), [38;5;124mf[39m[38;5;124m"[39m[38;5;124mSelection contains [39m[38;5;132;01m{[39;00m[38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39mcells)[38;5;132;01m}[39;00m[38;5;124m cells, not 1[39m[38;5;124m"[39m
[1;32m     66[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m

[0;31mAssertionError[0m: Selection contains 2 cells, not 1

